### ISSUE TITLE
Test for The Lancers is too simple

### ISSUE THREAD

**Issue by destitutus** [XanderVi/checkio-missions-set-war#19]
Looks like test is too simple for The Lancers task
Just adding a class of Lancer allow to pass all test
Probably is good to add a case then lancers are wins because of additional damage

```py
battle = Battle()
army_1 = Army()
army_2 = Army()
army_1.add_units(Lancer, 2)
army_2.add_units(Warrior, 3)
   
assert battle.fight(army_1, army_2) == True
```

**Comment by allburov** [comment]
@destitutus I suggest your test in https://github.com/XanderVi/checkio-missions-set-war/pull/24

**Comment by diegorodriguezv** [comment]
Hello! This problem is not solved yet. I just added the Lancer class but didn't implement the special attack for it and was able to "check" the mission as completed.
