### ISSUE TITLE
Rookie produce bug in some case

### ISSUE THREAD

**Issue by rydia001** [XanderVi/checkio-missions-set-war#5]
In "The Defenders" mission, a class Rookie(Warrior) is secretly added in judge, and they do not do super().__init__(). 
My code did not pass these test because my implementation assumes defense and is_alive are set as 0 and True as default at the init timing, respectively.
Please add super().__init()__ in Rookie().__init__() as in my pull request.

**Comment by XanderVi** [comment]
Thank you a lot)
I've merged your pull requests.
